apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    path: helm-guestboook
    repoURL: https://github.com/cloudgitops/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    server: https://guestbook.jamesknott.ai
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
