apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production 
  source:
    path: helm-guestbook 
    repoURL: https://github.com/cloudgitops/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc 
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
